### ISSUE TITLE
pmm helm chart suddenly broken (secret.name)

### ISSUE THREAD

**Issue by jogoossens** [percona/percona-helm-charts#393]
```
helm -n pmm install  --force -f=testvalues.yaml pmm 'percona/pmm'

W1016 22:58:29.540911 3262033 warnings.go:70] unknown field "spec.template.spec.containers[0].envFrom[2].name"
W1016 22:58:29.540929 3262033 warnings.go:70] unknown field "spec.template.spec.containers[0].envFrom[2].valueFrom"

```
The reason this fails is because secret.name is defined in testvalues.yaml
```
secret:
  name: pmm-admin
  create: false
...
```

As soon as I remove it, the install works ... What happened to it? A few days ago it just worked :)

**Comment by jogoossens** [comment]
Quite strange, seems the error is there all the time somehow suddenly

helm -n pmm install pmm \
--set secret.create=false \
--set secret.name=pmm-secret \
percona/pmm
W1016 23:11:26.857599 3266855 warnings.go:70] unknown field "spec.template.spec.containers[0].envFrom[2].name"
W1016 23:11:26.857617 3266855 warnings.go:70] unknown field "spec.template.spec.containers[0].envFrom[2].valueFrom"

Not sure where this comes from, it doesn't seem that it was there before

**Comment by jogoossens** [comment]
OK finally used just an older version and all works 100% ok

chart_version: "1.3.16"

It's clearly 1.3.17 which is just broken ...

By coincidence we just updated a bunch of code, so we were looking in the wrong direction, a few hours well spent :| :)

**Comment by dennis-paqtcom** [comment]
It's because of this change in the latest version:

```
{{ if .Values.secret.create }}
env:
``` 

Should be: 

```
env:
{{ if .Values.secret.create }}
```

**Comment by BupycHuk** [comment]
Fixed in #396

**Comment by SamuraiPrinciple** [comment]
I don't think this fixes the issue (at least not in backwards-compatible way) because `secret.create` still cannot be `false` (which would cause an error because stateful set would be trying to mount non-existing secret).

**Comment by BupycHuk** [comment]
@SamuraiPrinciple that will be fixed with #397

**Comment by SamuraiPrinciple** [comment]
That's great - much appreciated!
